// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vRqgrquCKld2sjllZ84_F5r8QcEdWZ0',
    appId: '1:961258913777:web:ee772d5904733db99a8e50',
    messagingSenderId: '961258913777',
    projectId: 'gteclms',
    authDomain: 'gteclms.firebaseapp.com',
    storageBucket: 'gteclms.firebasestorage.app',
    measurementId: 'G-ZVFTW6MP87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDl5a-o3q7hCDg1iDK8i4bHIh2DVUp_e4',
    appId: '1:961258913777:android:a2d87ee86151a6489a8e50',
    messagingSenderId: '961258913777',
    projectId: 'gteclms',
    storageBucket: 'gteclms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8RRlkoNDtGo367bD9Lyf_0Y5-54-XYHc',
    appId: '1:961258913777:ios:bda1bab549c1032a9a8e50',
    messagingSenderId: '961258913777',
    projectId: 'gteclms',
    storageBucket: 'gteclms.firebasestorage.app',
    iosBundleId: 'com.example.gtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8RRlkoNDtGo367bD9Lyf_0Y5-54-XYHc',
    appId: '1:961258913777:ios:bda1bab549c1032a9a8e50',
    messagingSenderId: '961258913777',
    projectId: 'gteclms',
    storageBucket: 'gteclms.firebasestorage.app',
    iosBundleId: 'com.example.gtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0vRqgrquCKld2sjllZ84_F5r8QcEdWZ0',
    appId: '1:961258913777:web:24760fea43ad8d1d9a8e50',
    messagingSenderId: '961258913777',
    projectId: 'gteclms',
    authDomain: 'gteclms.firebaseapp.com',
    storageBucket: 'gteclms.firebasestorage.app',
    measurementId: 'G-12V9DFMKYK',
  );

}